### PR TITLE
Added example which prints all learn events

### PR DESCRIPTION
**Pull request by miloserdow**
Now more meaningful example ;)

### CODE REVIEW

**Comment by mehanig** [comment]
Yes, much more, and also good idea!

Print formatting is a little bit weird, but as example it's ok.
Thank you.
screen shot 2016-06-02 at 1 29 35 pm

**Comment by vyahhi** [comment]
Oops, I thought we have removed events from API.
cc @andrvb ;)

**Comment by mehanig** [comment]
@vyahhi I've discussed with @psviderski yesterday about this endpoint, for us it's also unclear why it's open for everyone.
Might be, some pages at front-end using it, but i'm not sure if it's good idea.

**Comment by vyahhi** [comment]
For https://stepic.org/notifications/events, but we were going to remove it. AFAIK it's staff only now.

**Pull request merged**
