### PR TITLE
Prettify examples. Brought into conformity with PEP8.

### PR DESCRIPTION
**Pull request by GreenRiverRUS**
Prettify examples. Brought into conformity with PEP8.
Add token checking, remove unnecessary json.loads() usage

JetBrains Internship Task7 by Vadim Mazaev (vadim-mazaev mail.ru)

### CODE REVIEW

**Comment by GreenRiverRUS** [comment]
Не могу понять, почему Travis падает :(

**Comment by mehanig** [comment]
Good, but can't merge
please resolve conflicts.

**Comment by GreenRiverRUS** [comment]
Fixed

**Comment by mehanig** [comment]
good!

**Pull request merged**
